### ISSUE TITLE
WebComponents meta repo refactoring for v1

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/webcomponentsjs#657]
* [x] branch master for "v0" (v1 branch will eventually be moved to master): https://github.com/webcomponents/webcomponentsjs/tree/v0
* [x] remove unused polyfills for v1
  * [x] MutationObserver
  * [x] ShadowCSS
  * [x] ShadowDOM
  * [x] WeakMap
* [x] separate polyfills to separate repos
  * [x] HTMLImports (coordinate with v1 HTMLImports owner)
  * [x] Template: Moved to `webcomponents/template`
  * [x] URL: Moved `Polymer/URL` to `webcomponents/URL` and ported the 2 changes
  * [x] "Platform" polyfill (dom+lang minus unneeded stuff): https://github.com/webcomponents/webcomponents-platform
    * constructable events
    * ES6 stuff (Array.from, Object.assign)
  * [x] Remove code for unneeded stuff:
    * Function.prototype.bind
    * requestAnimationFrame
    * performance.now
    * [x] Promise
    * [x] legacy CustomElements.takeRecords
  * [ ] Leave as wcjs-specific code but clean up
    * flag handling (pre-polyfill)
    * WebComponentsReady event `post-polyfill.js` (TBD -- needs discussion)
    * unresolved styling `unresolved.js` (TBD -- needs discussion)
* No longer needed since we're going to try to use es6-promise: update [polymer Promise polyfill](https://github.com/polymerlabs/promise-polyfill) to remove Polymer dependency & use as replacement for wcjs Promise polyfill
* [ ] "everything together" build
    * [ ] figure out how the new conditional loading works with the timing of other polyfills the user needs to load
* [ ] normalize test & build infrastructure between all separate polyfill repos
* [ ] update readme

**Comment by TimvdLippe** [comment]
@azakus I think that all points in this issue have been addressed and that it can be closed.
